apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d4uw03344-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d4uw03344-nodejs 
  name: d4uw03344-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: d4uw03344-nodejs 
